'use client';

import React, { useState } from 'react';
import Sidebar from '@/components/layout/Sidebar/Sidebar';
import OnboardingWizard from '@/components/features/Onboarding/OnboardingWizard';
import { 
  FiCalendar, 
  FiClock, 
  FiCheckCircle, 
  FiRefreshCw, 
  FiBookOpen, 
  FiCpu, 
  FiHelpCircle,
  FiSliders,
  FiSliders as FiAdjust
} from 'react-icons/fi';
import styles from './planner.module.css';

interface AIPracticeTask {
  id: string;
  subject: string;
  title: string;
  type: 'AI Practice Assignment' | 'AI Diagnostic Quiz';
  estimatedTime: string;
  status: 'Pending' | 'Completed' | 'Auto-Shifted';
  aiReasoning: string;
}

export default function PlannerPage() {
  const [isSetupOpen, setIsSetupOpen] = useState(false);
  const [dailyHoursTarget, setDailyHoursTarget] = useState<number>(2);

  // AI Self-Generated Practice Plan (Not University Homework)
  const [practicePlan, setPracticePlan] = useState<AIPracticeTask[]>([
    {
      id: '1',
      subject: 'CS401 - Artificial Intelligence',
      title: 'Practice Assignment 1: Implement A* Search Logic',
      type: 'AI Practice Assignment',
      estimatedTime: '45 mins',
      status: 'Pending',
      aiReasoning: 'Generated by AI based on your core AI course outline.',
    },
    {
      id: '2',
      subject: 'CS401 - Artificial Intelligence',
      title: 'Diagnostic Quiz 1: Heuristics & Admissibility (5 Questions)',
      type: 'AI Diagnostic Quiz',
      estimatedTime: '15 mins',
      status: 'Pending',
      aiReasoning: 'Self-assessment quiz to test topic mastery.',
    },
    {
      id: '3',
      subject: 'SE302 - Software Architecture',
      title: 'Practice Assignment 2: Microservices Diagram Case Study',
      type: 'AI Practice Assignment',
      estimatedTime: 'Auto-Shifted',
      status: 'Auto-Shifted',
      aiReasoning: 'Shifted +1 day automatically because yesterday was skipped. Zero penalties applied.',
    },
  ]);

  const toggleTask = (id: string) => {
    setPracticePlan((prev) =>
      prev.map((item) =>
        item.id === id
          ? { ...item, status: item.status === 'Completed' ? 'Pending' : 'Completed' }
          : item
      )
    );
  };

  return (
    <div className={styles.plannerLayout}>
      <Sidebar onOpenSetupModal={() => setIsSetupOpen(true)} />

      <main className={styles.mainContent}>
        {/* Top Header */}
        <header className={styles.topHeader}>
          <div>
            <h1 className={styles.pageTitle}>Personalized Study Plan</h1>
            <p className={styles.pageSubtitle}>
              Autonomous AI-generated practice assignments and diagnostic quizzes tailored to your course.
            </p>
          </div>

          <button type="button" className={styles.aiSyncBtn}>
            <FiRefreshCw /> Recalibrate Schedule
          </button>
        </header>

        {/* Adaptive Zero-Penalty Banner */}
        <div className={styles.adaptiveBanner}>
          <div className={styles.bannerInfo}>
            <FiCpu className={styles.cpuIcon} />
            <div>
              <h3>Zero-Penalty Adaptive Engine Active</h3>
              <p>Missed a study day? Your roadmap automatically reschedules without guilt or accumulated backlog.</p>
            </div>
          </div>
          <span className={styles.adaptiveBadge}>Flexible Pacing</span>
        </div>

        {/* Quick Pace Adjustment Controls */}
        <div className={styles.paceCard}>
          <div className={styles.paceHeader}>
            <FiSliders className={styles.paceIcon} />
            <div>
              <h4>Adjust Daily Study Target</h4>
              <p>Change your target hours anytime; AI will instantly rebalance the practice load.</p>
            </div>
          </div>
          <div className={styles.sliderControl}>
            <input 
              type="range" 
              min="1" 
              max="6" 
              value={dailyHoursTarget}
              onChange={(e) => setDailyHoursTarget(parseInt(e.target.value))}
              className={styles.rangeInput}
            />
            <span className={styles.hoursDisplay}>{dailyHoursTarget} Hours / Day</span>
          </div>
        </div>

        {/* Generated Practice Roadmap */}
        <section className={styles.workspaceSection}>
          <div className={styles.sectionHeader}>
            <h2 className={styles.sectionTitle}>AI-Generated Practice Tasks for Today</h2>
            <span className={styles.disclaimerBadge}>
              <FiHelpCircle /> Independent Self-Study (Not College Homework)
            </span>
          </div>

          <div className={styles.taskList}>
            {practicePlan.map((item) => (
              <div 
                key={item.id} 
                className={item.status === 'Completed' ? styles.completedTaskRow : styles.taskRow}
              >
                <button 
                  type="button" 
                  onClick={() => toggleTask(item.id)}
                  className={styles.checkBtn}
                >
                  <FiCheckCircle className={item.status === 'Completed' ? styles.checkedIcon : styles.uncheckedIcon} />
                </button>

                <div className={styles.taskDetails}>
                  <div className={styles.subjectRow}>
                    <span className={styles.subjectTag}><FiBookOpen /> {item.subject}</span>
                    <span className={item.type === 'AI Diagnostic Quiz' ? styles.quizBadge : styles.assignmentBadge}>
                      {item.type}
                    </span>
                    {item.status === 'Auto-Shifted' && (
                      <span className={styles.shiftedBadge}>Auto-Rescheduled (No Penalty)</span>
                    )}
                  </div>
                  <h3 className={styles.taskTitle}>{item.title}</h3>
                  <p className={styles.aiReasoningText}>{item.aiReasoning}</p>
                </div>

                <div className={styles.dueDateBadge}>
                  <FiClock /> {item.estimatedTime}
                </div>
              </div>
            ))}
          </div>
        </section>
      </main>

      {/* Setup Modal */}
      {isSetupOpen && (
        <div className={styles.modalOverlay} onClick={() => setIsSetupOpen(false)}>
          <div className={styles.modalContainer} onClick={(e) => e.stopPropagation()}>
            <button 
              type="button" 
              className={styles.closeModalBtn} 
              onClick={() => setIsSetupOpen(false)}
            >
              ✕
            </button>
            <OnboardingWizard />
          </div>
        </div>
      )}
    </div>
  );
}